// --- 1. The NEW Questions List (136 Questions from sheet.html) ---
// This file is designed to be imported by logic.js
// Category names have been excluded from the 'name' field as requested.
const shortcuts = [
    { name: "Show/Hide UI", win: ['ctrlKey', '\\'], mac: ['metaKey', '\\'], difficulty: "easy" },
    { name: "Component search", win: ['shiftKey', 'i'], mac: ['shiftKey', 'i'], difficulty: "easy" },
    { name: "Actions... (Search menus, commands etc)", win: ['ctrlKey', 'p'], mac: ['metaKey', 'p'], difficulty: "easy" },
    { name: "Actions... (Search menus, commands)", win: ['ctrlKey', 'k'], mac: ['metaKey', 'k'], difficulty: "easy" },
    { name: "Move tool", win: ['v'], mac: ['v'], difficulty: "easy" },
    { name: "Frame tool", win: ['f'], mac: ['f'], difficulty: "easy" },
    { name: "Pen tool", win: ['p'], mac: ['p'], difficulty: "easy" },
    { name: "Pencil tool", win: ['shiftKey', 'p'], mac: ['shiftKey', 'p'], difficulty: "hard" },
    { name: "Text tool", win: ['t'], mac: ['t'], difficulty: "easy" },
    { name: "Rectangle tool", win: ['r'], mac: ['r'], difficulty: "easy" },
    { name: "Ellipse tool", win: ['o'], mac: ['o'], difficulty: "easy" },
    { name: "Line tool", win: ['l'], mac: ['l'], difficulty: "easy" },
    { name: "Arrow tool", win: ['shiftKey', 'l'], mac: ['shiftKey', 'l'], difficulty: "hard" },
    { name: "View comments", win: ['c'], mac: ['c'], difficulty: "easy" },
    { name: "Show/hide comments", win: ['shiftKey', 'c'], mac: ['shiftKey', 'c'], difficulty: "hard" },
    { name: "Annotation tool", win: ['y'], mac: ['y'], difficulty: "hard" },
    { name: "Slice tool", win: ['s'], mac: ['s'], difficulty: "easy" },
    { name: "Colour picker", win: ['i'], mac: ['i'], difficulty: "easy" },
    { name: "Show/Hide UI", win: ['ctrlKey', '\\'], mac: ['metaKey', '\\'], difficulty: "easy" },
    { name: "Multiplayer cursors", win: ['ctrlKey', 'altKey', '\\'], mac: ['metaKey', 'altKey', '\\'], difficulty: "hard" },
    { name: "Rulers", win: ['shiftKey', 'r'], mac: ['shiftKey', 'r'], difficulty: "easy" },
    { name: "Show outlines", win: ['ctrlKey', 'shiftKey', 'o'], mac: ['metaKey', 'shiftKey', 'o'], difficulty: "hard" },
    { name: "Pixel preview", win: ['ctrlKey', 'shiftKey', 'p'], mac: ['metaKey', 'shiftKey', 'p'], difficulty: "hard" },
    { name: "Layout grids", win: ['shiftKey', 'g'], mac: ['shiftKey', 'g'], difficulty: "easy" },
    { name: "Pixel grid", win: ['shiftKey', "'"], mac: ['shiftKey', "'"], difficulty: "hard" },
    { name: "Open layer panel", win: ['altKey', '1'], mac: ['altKey', '1'], difficulty: "hard" },
    { name: "Show assets", win: ['altKey', '2'], mac: ['altKey', '2'], difficulty: "hard" },
    { name: "Team library", win: ['altKey', '3'], mac: ['altKey', '3'], difficulty: "hard" },
    { name: "Open design panel", win: ['altKey', '8'], mac: ['altKey', '8'], difficulty: "hard" },
    { name: "Open prototype panel", win: ['altKey', '9'], mac: ['altKey', '9'], difficulty: "hard" },
    { name: "Pan", win: ['space'], mac: ['space'], difficulty: "easy" },
    { name: "Previous page", win: ['pageup'], mac: ['pageup'], difficulty: "hard" },
    { name: "Next page", win: ['pagedown'], mac: ['pagedown'], difficulty: "hard" },
    { name: "Find previous frame", win: ['home'], mac: ['home'], difficulty: "hard" },
    { name: "Find next frame", win: ['end'], mac: ['end'], difficulty: "hard" },
    { name: "Zoom in", win: ['ctrlKey', '='], mac: ['metaKey', '='], difficulty: "hard" },
    { name: "Zoom out", win: ['ctrlKey', '-'], mac: ['metaKey', '-'], difficulty: "hard" },
    { name: "Zoom to 100%", win: ['ctrlKey', '0'], mac: ['metaKey', '0'], difficulty: "hard" },
    { name: "Zoom to fit", win: ['shiftKey', '1'], mac: ['shiftKey', '1'], difficulty: "hard" },
    { name: "Zoom to selection", win: ['shiftKey', '2'], mac: ['shiftKey', '2'], difficulty: "hard" },
    { name: "Zoom to previous frame", win: ['shiftKey', 'n'], mac: ['shiftKey', 'n'], difficulty: "hard" },
    { name: "Zoom to next frame", win: ['n'], mac: ['n'], difficulty: "easy" },
    { name: "Bold", win: ['ctrlKey', 'b'], mac: ['metaKey', 'b'], difficulty: "easy" },
    { name: "Italic", win: ['ctrlKey', 'i'], mac: ['metaKey', 'i'], difficulty: "easy" },
    { name: "Create link", win: ['ctrlKey', 'shiftKey', 'u'], mac: ['metaKey', 'shiftKey', 'u'], difficulty: "easy" },
    { name: "Strikethrough", win: ['ctrlKey', 'shiftKey', 'x'], mac: ['metaKey', 'shiftKey', 'x'], difficulty: "easy" },
    { name: "Turn bulleted list on/off", win: ['shiftKey', 'ctrlKey', '7'], mac: ['shiftKey', 'metaKey', '7'], difficulty: "hard" },
    { name: "Turn numbered list on/off", win: ['shiftKey', 'ctrlKey', '8'], mac: ['shiftKey', 'metaKey', '8'], difficulty: "hard" },
    { name: "Text align left", win: ['ctrlKey', 'altKey', 'l'], mac: ['metaKey', 'altKey', 'l'], difficulty: "hard" },
    { name: "Text align center", win: ['ctrlKey', 'altKey', 't'], mac: ['metaKey', 'altKey', 't'], difficulty: "hard" },
    { name: "Text align right", win: ['ctrlKey', 'altKey', 'r'], mac: ['metaKey', 'altKey', 'r'], difficulty: "hard" },
    { name: "Text align justified", win: ['ctrlKey', 'altKey', 'j'], mac: ['metaKey', 'altKey', 'j'], difficulty: "hard" },
    { name: "Increase font size", win: ['shiftKey', 'ctrlKey', '>'], mac: ['shiftKey', 'metaKey', '>'], difficulty: "hard" },
    { name: "Decrease font size", win: ['shiftKey', 'ctrlKey', '<'], mac: ['shiftKey', 'metaKey', '<'], difficulty: "hard" },
    { name: "Increase font weight", win: ['ctrlKey', 'altKey', '>'], mac: ['metaKey', 'altKey', '>'], difficulty: "hard" },
    { name: "Decrease font weight", win: ['ctrlKey', 'altKey', '<'], mac: ['metaKey', 'altKey', '<'], difficulty: "hard" },
    { name: "Increase letter spacing", win: ['altKey', '<'], mac: ['altKey', '>'], difficulty: "hard" },
    { name: "Decrease letter spacing", win: ['altKey', '>'], mac: ['altKey', '<'], difficulty: "hard" },
    { name: "Increase line height", win: ['altKey', 'shiftKey', '>'], mac: ['altKey', 'shiftKey', '<'], difficulty: "hard" },
    { name: "Decrease line height", win: ['altKey', 'shiftKey', '<'], mac: ['altKey', 'shiftKey', '>'], difficulty: "hard" },
    { name: "Underline", win: ['ctrlKey', 'u'], mac: ['metaKey', 'u'], difficulty: "hard" },
    { name: "Pen", win: ['p'], mac: ['p'], difficulty: "easy" },
    { name: "Pencil", win: ['shiftKey', 'p'], mac: ['shiftKey', 'p'], difficulty: "hard" },
    { name: "Paint (vector editing)", win: ['shiftKey', 'b'], mac: ['shiftKey', 'b'], difficulty: "hard" },
    { name: "Cut (vector editing)", win: ['x'], mac: ['x'], difficulty: "hard" },
    { name: "Remove fill", win: ['altKey', '/'], mac: ['altKey', '/'], difficulty: "easy" },
    { name: "Remove stroke", win: ['ctrlKey', '/'], mac: ['metaKey', '/'], difficulty: "easy" },
    { name: "Swap fill and stroke", win: ['shiftKey', 'x'], mac: ['shiftKey', 'x'], difficulty: "hard" },
    { name: "Outline stroke", win: ['ctrlKey', 'altKey', 'o'], mac: ['metaKey', 'altKey', 'o'], difficulty: "hard" },
    { name: "Flatten", win: ['ctrlKey', 'shiftKey', 'f'], mac: ['metaKey', 'shiftKey', 'f'], difficulty: "hard" },
    { name: "Join selection", win: ['ctrlKey', 'j'], mac: ['metaKey', 'j'], difficulty: "hard" },
    { name: "Delete and heal selection", win: ['shiftKey', 'delete'], mac: ['shiftKey', 'delete'], difficulty: "hard" },
    { name: "Select all", win: ['ctrlKey', 'a'], mac: ['metaKey', 'a'], difficulty: "easy" },
    { name: "Select inverse", win: ['ctrlKey', 'shiftKey', 'a'], mac: ['metaKey', 'shiftKey', 'a'], difficulty: "easy" },
    { name: "Select none", win: ['escape'], mac: ['escape'], difficulty: "easy" },
    { name: "Select children", win: ['enter'], mac: ['enter'], difficulty: "hard" },
    { name: "Select parent", win: ['\\'], mac: ['\\'], difficulty: "hard" },
    { name: "Select next sibling", win: ['tab'], mac: ['tab'], difficulty: "hard" },
    { name: "Select previous sibling", win: ['shiftKey', 'tab'], mac: ['shiftKey', 'tab'], difficulty: "hard" },
    { name: "Select matching layers", win: ['ctrlKey', 'altKey', 'a'], mac: ['metaKey', 'altKey', 'a'], difficulty: "easy" },
    { name: "Group selection", win: ['ctrlKey', 'g'], mac: ['metaKey', 'g'], difficulty: "easy" },
    { name: "Ungroup selection", win: ['ctrlKey', 'backspace'], mac: ['metaKey', 'backspace'], difficulty: "easy" },
    { name: "Frame selection", win: ['ctrlKey', 'altKey', 'g'], mac: ['metaKey', 'altKey', 'g'], difficulty: "hard" },
    { name: "Show/Hide selection", win: ['ctrlKey', 'shiftKey', 'h'], mac: ['metaKey', 'shiftKey', 'h'], difficulty: "hard" },
    { name: "Lock/Unlock selection", win: ['ctrlKey', 'shiftKey', 'l'], mac: ['metaKey', 'shiftKey', 'l'], difficulty: "hard" },
    { name: "Copy", win: ['ctrlKey', 'c'], mac: ['metaKey', 'c'], difficulty: "easy" },
    { name: "Cut", win: ['ctrlKey', 'x'], mac: ['metaKey', 'x'], difficulty: "easy" },
    { name: "Paste", win: ['ctrlKey', 'v'], mac: ['metaKey', 'v'], difficulty: "easy" },
    { name: "Paste to replace", win: ['ctrlKey', 'shiftKey', 'r'], mac: ['metaKey', 'shiftKey', 'r'], difficulty: "easy" },
    { name: "Paste over selection", win: ['ctrlKey', 'shiftKey', 'v'], mac: ['metaKey', 'shiftKey', 'v'], difficulty: "easy" },
    { name: "Duplicate", win: ['ctrlKey', 'd'], mac: ['metaKey', 'd'], difficulty: "easy" },
    { name: "Rename selection", win: ['ctrlKey', 'r'], mac: ['metaKey', 'r'], difficulty: "easy" },
    { name: "Find", win: ['ctrlKey', 'f'], mac: ['metaKey', 'f'], difficulty: "easy" },
    { name: "Copy as PNG", win: ['ctrlKey', 'shiftKey', 'c'], mac: ['metaKey', 'shiftKey', 'c'], difficulty: "easy" },
    { name: "Copy properties", win: ['ctrlKey', 'altKey', 'c'], mac: ['metaKey', 'altKey', 'c'], difficulty: "easy" },
    { name: "Paste properties", win: ['ctrlKey', 'altKey', 'v'], mac: ['metaKey', 'altKey', 'v'], difficulty: "easy" },
    { name: "Flip horizontal", win: ['shiftKey', 'h'], mac: ['shiftKey', 'h'], difficulty: "easy" },
    { name: "Flip vertical", win: ['shiftKey', 'v'], mac: ['shiftKey', 'v'], difficulty: "easy" },
    { name: "Use as mask", win: ['ctrlKey', 'altKey', 'm'], mac: ['metaKey', 'altKey', 'm'], difficulty: "hard" },
    { name: "Edit Shape or image", win: ['enter'], mac: ['enter'], difficulty: "easy" },
    { name: "Place image/video...", win: ['ctrlKey', 'shiftKey', 'k'], mac: ['metaKey', 'shiftKey', 'k'], difficulty: "easy" },
    { name: "Set opacity to 100%", win: ['0'], mac: ['0'], difficulty: "easy" },
    { name: "Set opacity to 50%", win: ['5'], mac: ['5'], difficulty: "easy" },
    { name: "Set opacity to 10%", win: ['1'], mac: ['1'], difficulty: "easy" },
    { name: "Set opacity to 0%", win: ['0', '0'], mac: ['0', '0'], difficulty: "easy" },
    { name: "Bring to front", win: [']'], mac: [']'], difficulty: "easy" },
    { name: "Send to back", win: ['['], mac: ['['], difficulty: "easy" },
    { name: "Bring forward", win: ['ctrlKey', ']'], mac: ['metaKey', ']'], difficulty: "easy" },
    { name: "Send backward", win: ['ctrlKey', '['], mac: ['metaKey', '['], difficulty: "easy" },
    { name: "Align left", win: ['altKey', 'a'], mac: ['altKey', 'a'], difficulty: "hard" },
    { name: "Align top", win: ['altKey', 'w'], mac: ['altKey', 'w'], difficulty: "hard" },
    { name: "Align right", win: ['altKey', 'd'], mac: ['altKey', 'd'], difficulty: "hard" },
    { name: "Align bottom", win: ['altKey', 's'], mac: ['altKey', 's'], difficulty: "hard" },
    { name: "Align horizontal centers", win: ['altKey', 'h'], mac: ['altKey', 'h'], difficulty: "hard" },
    { name: "Align vertical centers", win: ['altKey', 'v'], mac: ['altKey', 'v'], difficulty: "hard" },
    { name: "Distribute horizontal spacing", win: ['altKey', 'shiftKey', 'h'], mac: ['altKey', 'shiftKey', 'h'], difficulty: "hard" },
    { name: "Distribute vertical spacing", win: ['altKey', 'shiftKey', 'v'], mac: ['altKey', 'shiftKey', 'v'], difficulty: "hard" },
    { name: "Tidy up", win: ['ctrlKey', 'altKey', 'shiftKey', 't'], mac: ['metaKey', 'altKey', 'shiftKey', 't'], difficulty: "hard" },
    { name: "Add auto layout", win: ['shiftKey', 'a'], mac: ['shiftKey', 'a'], difficulty: "easy" },
    { name: "Remove auto layout", win: ['altKey', 'shiftKey', 'a'], mac: ['altKey', 'shiftKey', 'a'], difficulty: "easy" },
    { name: "Suggest auto layout", win: ['ctrlKey', 'altKey', 'shiftKey', 'a'], mac: ['metaKey', 'altKey', 'shiftKey', 'a'], difficulty: "easy" },
    { name: "Show assets", win: ['altKey', '2'], mac: ['altKey', '2'], difficulty: "hard" },
    { name: "Team library", win: ['altKey', '3'], mac: ['altKey', '3'], difficulty: "hard" },
    { name: "Create component", win: ['ctrlKey', 'altKey', 'k'], mac: ['metaKey', 'altKey', 'k'], difficulty: "hard" },
    { name: "Detach instance", win: ['ctrlKey', 'altKey', 'b'], mac: ['metaKey', 'altKey', 'b'], difficulty: "hard" },
    { name: "Component search", win: ['shiftKey', 'i'], mac: ['shiftKey', 'i'], difficulty: "hard" },
    { name: "Show figma Keyboard shortcuts", win: ['ctrlKey', 'shiftKey', '?'], mac: ['metaKey', 'shiftKey', '?'], difficulty: "hard" },
    { name: "Export", win: ['ctrlKey', 'shiftKey', 'e'], mac: ['metaKey', 'shiftKey', 'e'], difficulty: "easy" },
    { name: "Present prototype", win: ['ctrlKey', 'altKey', 'enter'], mac: ['metaKey', 'altKey', 'enter'], difficulty: "easy" },
    { name: "Preview prototype", win: ['shiftKey', 'space'], mac: ['shiftKey', 'space'], difficulty: "easy" },
    { name: "Restart prototype", win: ['r'], mac: ['r'], difficulty: "easy" },
    { name: "Content scale in prototype", win: ['z'], mac: ['z'], difficulty: "hard" },
    { name: "Run last plugin", win: ['ctrlKey', 'altKey', 'p'], mac: ['metaKey', 'altKey', 'p'], difficulty: "easy" },
    { name: "Cursor chat", win: ['/'], mac: ['/'], difficulty: "easy" },
    { name: "Switch to dev mode", win: ['shiftKey', 'd'], mac: ['shiftKey', 'd'], difficulty: "hard" },
    { name: "Copy file link", win: ['ctrlKey', 'l'], mac: ['metaKey', 'l'], difficulty: "easy" }
];

// This line makes the array "importable" by logic.js
export { shortcuts };
