// --- 1. The NEW Questions List (135 Questions from sheet.html) ---
// This file is designed to be imported by logic.js
const shortcuts = [
    { name: "Show/Hide UI (Essential)", win: ['ctrlKey', '\\'], mac: ['metaKey', '\\'], difficulty: "easy" },
    { name: "Component search (Essential)", win: ['shiftKey', 'i'], mac: ['shiftKey', 'i'], difficulty: "easy" },
    { name: "Actions... (Search menus, commands etc) (Essential)", win: ['ctrlKey', 'p'], mac: ['metaKey', 'p'], difficulty: "easy" },
    { name: "Actions... (Search menus, commands) (Essential)", win: ['ctrlKey', 'k'], mac: ['metaKey', 'k'], difficulty: "easy" },
    { name: "Move tool (Tools)", win: ['v'], mac: ['v'], difficulty: "easy" },
    { name: "Frame tool (Tools)", win: ['f'], mac: ['f'], difficulty: "easy" },
    { name: "Pen tool (Tools)", win: ['p'], mac: ['p'], difficulty: "easy" },
    { name: "Pencil tool (Tools)", win: ['shiftKey', 'p'], mac: ['shiftKey', 'p'], difficulty: "hard" },
    { name: "Text tool (Tools)", win: ['t'], mac: ['t'], difficulty: "easy" },
    { name: "Rectangle tool (Tools)", win: ['r'], mac: ['r'], difficulty: "easy" },
    { name: "Ellipse tool (Tools)", win: ['o'], mac: ['o'], difficulty: "easy" },
    { name: "Line tool (Tools)", win: ['l'], mac: ['l'], difficulty: "easy" },
    { name: "Arrow tool (Tools)", win: ['shiftKey', 'l'], mac: ['shiftKey', 'l'], difficulty: "hard" },
    { name: "View comments (Tools)", win: ['c'], mac: ['c'], difficulty: "easy" },
    { name: "Show/hide comments (Tools)", win: ['shiftKey', 'c'], mac: ['shiftKey', 'c'], difficulty: "hard" },
    { name: "Annotation tool (Tools)", win: ['y'], mac: ['y'], difficulty: "hard" },
    { name: "Slice tool (Tools)", win: ['s'], mac: ['s'], difficulty: "easy" },
    { name: "Colour picker (Tools)", win: ['i'], mac: ['i'], difficulty: "easy" },
    { name: "Show/Hide UI (View)", win: ['ctrlKey', '\\'], mac: ['metaKey', '\\'], difficulty: "easy" },
    { name: "Multiplayer cursors (View)", win: ['ctrlKey', 'altKey', '\\'], mac: ['metaKey', 'altKey', '\\'], difficulty: "hard" },
    { name: "Rulers (View)", win: ['shiftKey', 'r'], mac: ['shiftKey', 'r'], difficulty: "easy" },
    { name: "Show outlines (View)", win: ['ctrlKey', 'shiftKey', 'o'], mac: ['metaKey', 'shiftKey', 'o'], difficulty: "hard" },
    { name: "Pixel preview (View)", win: ['ctrlKey', 'shiftKey', 'p'], mac: ['metaKey', 'shiftKey', 'p'], difficulty: "hard" },
    { name: "Layout grids (View)", win: ['shiftKey', 'g'], mac: ['shiftKey', 'g'], difficulty: "easy" },
    { name: "Pixel grid (View)", win: ['shiftKey', "'"], mac: ['shiftKey', "'"], difficulty: "hard" },
    { name: "Open layer panel (View)", win: ['altKey', '1'], mac: ['altKey', '1'], difficulty: "hard" },
    { name: "Show assets (View)", win: ['altKey', '2'], mac: ['altKey', '2'], difficulty: "hard" },
    { name: "Team library (View)", win: ['altKey', '3'], mac: ['altKey', '3'], difficulty: "hard" },
    { name: "Open design panel (View)", win: ['altKey', '8'], mac: ['altKey', '8'], difficulty: "hard" },
    { name: "Open prototype panel (View)", win: ['altKey', '9'], mac: ['altKey', '9'], difficulty: "hard" },
    { name: "Pan (Zoom)", win: ['space'], mac: ['space'], difficulty: "easy" },
    { name: "Previous page (Zoom)", win: ['pageup'], mac: ['pageup'], difficulty: "hard" },
    { name: "Next page (Zoom)", win: ['pagedown'], mac: ['pagedown'], difficulty: "hard" },
    { name: "Find previous frame (Zoom)", win: ['home'], mac: ['home'], difficulty: "hard" },
    { name: "Find next frame (Zoom)", win: ['end'], mac: ['end'], difficulty: "hard" },
    { name: "Zoom in (Zoom)", win: ['ctrlKey', '='], mac: ['metaKey', '='], difficulty: "hard" },
    { name: "Zoom out (Zoom)", win: ['ctrlKey', '-'], mac: ['metaKey', '-'], difficulty: "hard" },
    { name: "Zoom to 100% (Zoom)", win: ['ctrlKey', '0'], mac: ['metaKey', '0'], difficulty: "hard" },
    { name: "Zoom to fit (Zoom)", win: ['shiftKey', '1'], mac: ['shiftKey', '1'], difficulty: "hard" },
    { name: "Zoom to selection (Zoom)", win: ['shiftKey', '2'], mac: ['shiftKey', '2'], difficulty: "hard" },
    { name: "Zoom to previous frame (Zoom)", win: ['shiftKey', 'n'], mac: ['shiftKey', 'n'], difficulty: "hard" },
    { name: "Zoom to next frame (Zoom)", win: ['n'], mac: ['n'], difficulty: "hard" },
    { name: "Bold (Text)", win: ['ctrlKey', 'b'], mac: ['metaKey', 'b'], difficulty: "easy" },
    { name: "Italic (Text)", win: ['ctrlKey', 'i'], mac: ['metaKey', 'i'], difficulty: "easy" },
    { name: "Create link (Text)", win: ['ctrlKey', 'k'], mac: ['metaKey', 'k'], difficulty: "easy" },
    { name: "Strikethrough (Text)", win: ['ctrlKey', 'shiftKey', 'u'], mac: ['metaKey', 'shiftKey', 'u'], difficulty: "easy" },
    { name: "Turn bulleted list on/off (Text)", win: ['shiftKey', 'ctrlKey', '7'], mac: ['shiftKey', 'metaKey', '7'], difficulty: "hard" },
    { name: "Turn numbered list on/off (Text)", win: ['shiftKey', 'ctrlKey', '8'], mac: ['shiftKey', 'metaKey', '8'], difficulty: "hard" },
    { name: "Text align left (Text)", win: ['ctrlKey', 'altKey', 'l'], mac: ['metaKey', 'altKey', 'l'], difficulty: "hard" },
    { name: "Text align center (Text)", win: ['ctrlKey', 'altKey', 't'], mac: ['metaKey', 'altKey', 't'], difficulty: "hard" },
    { name: "Text align right (Text)", win: ['ctrlKey', 'altKey', 'r'], mac: ['metaKey', 'altKey', 'r'], difficulty: "hard" },
    { name: "Text align justified (Text)", win: ['ctrlKey', 'altKey', 'j'], mac: ['metaKey', 'altKey', 'j'], difficulty: "hard" },
    { name: "Increase font size (Text)", win: ['shiftKey', 'ctrlKey', '>'], mac: ['shiftKey', 'metaKey', '>'], difficulty: "hard" },
    { name: "Decrease font size (Text)", win: ['shiftKey', 'ctrlKey', '<'], mac: ['shiftKey', 'metaKey', '<'], difficulty: "hard" },
    { name: "Increase font weight (Text)", win: ['ctrlKey', 'altKey', '>'], mac: ['metaKey', 'altKey', '>'], difficulty: "hard" },
    { name: "Decrease font weight (Text)", win: ['ctrlKey', 'altKey', '<'], mac: ['metaKey', 'altKey', '<'], difficulty: "hard" },
    { name: "Increase letter spacing (Text)", win: ['altKey', '<'], mac: ['altKey', '>'], difficulty: "hard" },
    { name: "Decrease letter spacing (Text)", win: ['altKey', '>'], mac: ['altKey', '<'], difficulty: "hard" },
    { name: "Increase line height (Text)", win: ['altKey', 'shiftKey', '>'], mac: ['altKey', 'shiftKey', '<'], difficulty: "hard" },
    { name: "Decrease line height (Text)", win: ['altKey', 'shiftKey', '<'], mac: ['altKey', 'shiftKey', '>'], difficulty: "hard" },
    { name: "Underline (Text)", win: ['ctrlKey', 'u'], mac: ['metaKey', 'u'], difficulty: "hard" },
    { name: "Pen (Shape)", win: ['p'], mac: ['p'], difficulty: "easy" },
    { name: "Pencil (Shape)", win: ['shiftKey', 'p'], mac: ['shiftKey', 'p'], difficulty: "hard" },
    { name: "Paint (vector editing) (Shape)", win: ['shiftKey', 'b'], mac: ['shiftKey', 'b'], difficulty: "hard" },
    { name: "Cut (vector editing) (Shape)", win: ['x'], mac: ['x'], difficulty: "easy" },
    { name: "Remove fill (Shape)", win: ['altKey', '/'], mac: ['altKey', '/'], difficulty: "hard" },
    { name: "Remove stroke (Shape)", win: ['ctrlKey', '/'], mac: ['metaKey', '/'], difficulty: "hard" },
    { name: "Swap fill and stroke (Shape)", win: ['shiftKey', 'x'], mac: ['shiftKey', 'x'], difficulty: "hard" },
    { name: "Outline stroke (Shape)", win: ['ctrlKey', 'altKey', 'o'], mac: ['metaKey', 'altKey', 'o'], difficulty: "hard" },
    { name: "Flatten (Shape)", win: ['ctrlKey', 'shiftKey', 'f'], mac: ['metaKey', 'shiftKey', 'f'], difficulty: "hard" },
    { name: "Join selection (Shape)", win: ['ctrlKey', 'j'], mac: ['metaKey', 'j'], difficulty: "hard" },
    { name: "Delete and heal selection (Shape)", win: ['shiftKey', 'delete'], mac: ['shiftKey', 'delete'], difficulty: "hard" },
    { name: "Select all (Selection)", win: ['ctrlKey', 'a'], mac: ['metaKey', 'a'], difficulty: "easy" },
    { name: "Select inverse (Selection)", win: ['ctrlKey', 'shiftKey', 'a'], mac: ['metaKey', 'shiftKey', 'a'], difficulty: "easy" },
    { name: "Select none (Selection)", win: ['escape'], mac: ['escape'], difficulty: "easy" },
    { name: "Select children (Selection)", win: ['enter'], mac: ['enter'], difficulty: "hard" },
    { name: "Select parent (Selection)", win: ['\\'], mac: ['\\'], difficulty: "hard" },
    { name: "Select next sibling (Selection)", win: ['tab'], mac: ['tab'], difficulty: "hard" },
    { name: "Select previous sibling (Selection)", win: ['shiftKey', 'tab'], mac: ['shiftKey', 'tab'], difficulty: "hard" },
    { name: "Select matching layers (Selection)", win: ['ctrlKey', 'altKey', 'a'], mac: ['metaKey', 'altKey', 'a'], difficulty: "easy" },
    { name: "Group selection (Selection)", win: ['ctrlKey', 'g'], mac: ['metaKey', 'g'], difficulty: "easy" },
    { name: "Ungroup selection (Selection)", win: ['ctrlKey', 'backspace'], mac: ['metaKey', 'backspace'], difficulty: "easy" },
    { name: "Frame selection (Selection)", win: ['ctrlKey', 'altKey', 'g'], mac: ['metaKey', 'altKey', 'g'], difficulty: "hard" },
    { name: "Show/Hide selection (Selection)", win: ['ctrlKey', 'shiftKey', 'h'], mac: ['metaKey', 'shiftKey', 'h'], difficulty: "hard" },
    { name: "Lock/Unlock selection (Selection)", win: ['ctrlKey', 'shiftKey', 'l'], mac: ['metaKey', 'shiftKey', 'l'], difficulty: "hard" },
    { name: "Copy (Edit)", win: ['ctrlKey', 'c'], mac: ['metaKey', 'c'], difficulty: "easy" },
    { name: "Cut (Edit)", win: ['ctrlKey', 'x'], mac: ['metaKey', 'x'], difficulty: "easy" },
    { name: "Paste (Edit)", win: ['ctrlKey', 'v'], mac: ['metaKey', 'v'], difficulty: "easy" },
    { name: "Paste to replace (Edit)", win: ['ctrlKey', 'shiftKey', 'r'], mac: ['metaKey', 'shiftKey', 'r'], difficulty: "easy" },
    { name: "Paste over selection (Edit)", win: ['ctrlKey', 'shiftKey', 'v'], mac: ['metaKey', 'shiftKey', 'v'], difficulty: "easy" },
    { name: "Duplicate (Edit)", win: ['ctrlKey', 'd'], mac: ['metaKey', 'd'], difficulty: "easy" },
    { name: "Rename selection (Edit)", win: ['ctrlKey', 'r'], mac: ['metaKey', 'r'], difficulty: "easy" },
    { name: "Find (Edit)", win: ['ctrlKey', 'f'], mac: ['metaKey', 'f'], difficulty: "easy" },
    { name: "Copy as PNG (Edit)", win: ['ctrlKey', 'shiftKey', 'c'], mac: ['metaKey', 'shiftKey', 'c'], difficulty: "easy" },
    { name: "Copy properties (Edit)", win: ['ctrlKey', 'altKey', 'c'], mac: ['metaKey', 'altKey', 'c'], difficulty: "easy" },
    { name: "Paste properties (Edit)", win: ['ctrlKey', 'altKey', 'v'], mac: ['metaKey', 'altKey', 'v'], difficulty: "easy" },
    { name: "Flip horizontal (Transform)", win: ['shiftKey', 'h'], mac: ['shiftKey', 'h'], difficulty: "easy" },
    { name: "Flip vertical (Transform)", win: ['shiftKey', 'v'], mac: ['shiftKey', 'v'], difficulty: "easy" },
    { name: "Use as mask (Transform)", win: ['ctrlKey', 'altKey', 'm'], mac: ['metaKey', 'altKey', 'm'], difficulty: "hard" },
    { name: "Edit Shape or image (Transform)", win: ['enter'], mac: ['enter'], difficulty: "easy" },
    { name: "Place image/video... (Transform)", win: ['ctrlKey', 'shiftKey', 'k'], mac: ['metaKey', 'shiftKey', 'k'], difficulty: "easy" },
    { name: "Set opacity to 100% (Transform)", win: ['0'], mac: ['0'], difficulty: "easy" },
    { name: "Set opacity to 50% (Transform)", win: ['5'], mac: ['5'], difficulty: "easy" },
    { name: "Set opacity to 10% (Transform)", win: ['1'], mac: ['1'], difficulty: "easy" },
    { name: "Set opacity to 0% (Transform)", win: ['0', '0'], mac: ['0', '0'], difficulty: "easy" },
    { name: "Bring to front (Arrange)", win: [']'], mac: [']'], difficulty: "easy" },
    { name: "Send to back (Arrange)", win: ['['], mac: ['['], difficulty: "easy" },
    { name: "Bring forward (Arrange)", win: ['ctrlKey', ']'], mac: ['metaKey', ']'], difficulty: "easy" },
    { name: "Send backward (Arrange)", win: ['ctrlKey', '['], mac: ['metaKey', '['], difficulty: "easy" },
    { name: "Align left (Arrange)", win: ['altKey', 'a'], mac: ['altKey', 'a'], difficulty: "hard" },
    { name: "Align top (Arrange)", win: ['altKey', 'w'], mac: ['altKey', 'w'], difficulty: "hard" },
    { name: "Align right (Arrange)", win: ['altKey', 'd'], mac: ['altKey', 'd'], difficulty: "hard" },
    { name: "Align bottom (Arrange)", win: ['altKey', 's'], mac: ['altKey', 's'], difficulty: "hard" },
    { name: "Align horizontal centers (Arrange)", win: ['altKey', 'h'], mac: ['altKey', 'h'], difficulty: "hard" },
    { name: "Align vertical centers (Arrange)", win: ['altKey', 'v'], mac: ['altKey', 'v'], difficulty: "hard" },
    { name: "Distribute horizontal spacing (Arrange)", win: ['altKey', 'shiftKey', 'h'], mac: ['altKey', 'shiftKey', 'h'], difficulty: "hard" },
    { name: "Distribute vertical spacing (Arrange)", win: ['altKey', 'shiftKey', 'v'], mac: ['altKey', 'shiftKey', 'v'], difficulty: "hard" },
    { name: "Tidy up (Arrange)", win: ['ctrlKey', 'altKey', 'shiftKey', 't'], mac: ['metaKey', 'altKey', 'shiftKey', 't'], difficulty: "hard" },
    { name: "Add auto layout (Arrange)", win: ['shiftKey', 'a'], mac: ['shiftKey', 'a'], difficulty: "easy" },
    { name: "Remove auto layout (Arrange)", win: ['altKey', 'shiftKey', 'a'], mac: ['altKey', 'shiftKey', 'a'], difficulty: "easy" },
    { name: "Suggest auto layout (Arrange)", win: ['ctrlKey', 'altKey', 'shiftKey', 'a'], mac: ['metaKey', 'altKey', 'shiftKey', 'a'], difficulty: "easy" },
    { name: "Show assets (Components)", win: ['altKey', '2'], mac: ['altKey', '2'], difficulty: "hard" },
    { name: "Team library (Components)", win: ['altKey', '3'], mac: ['altKey', '3'], difficulty: "hard" },
    { name: "Create component (Components)", win: ['ctrlKey', 'altKey', 'k'], mac: ['metaKey', 'altKey', 'k'], difficulty: "hard" },
    { name: "Detach instance (Components)", win: ['ctrlKey', 'altKey', 'b'], mac: ['metaKey', 'altKey', 'b'], difficulty: "hard" },
    { name: "Component search (Components)", win: ['shiftKey', 'i'], mac: ['shiftKey', 'i'], difficulty: "hard" },
    { name: "Show figma Keyboard shortcuts (Help)", win: ['ctrlKey', 'shiftKey', '?'], mac: ['metaKey', 'shiftKey', '?'], difficulty: "hard" },
    { name: "Export (Export)", win: ['ctrlKey', 'shiftKey', 'e'], mac: ['metaKey', 'shiftKey', 'e'], difficulty: "easy" },
    { name: "Present prototype (Prototype)", win: ['ctrlKey', 'altKey', 'enter'], mac: ['metaKey', 'altKey', 'enter'], difficulty: "easy" },
    { name: "Preview prototype (Prototype)", win: ['shiftKey', 'space'], mac: ['shiftKey', 'space'], difficulty: "easy" },
    { name: "Restart prototype (Prototype)", win: ['r'], mac: ['r'], difficulty: "easy" },
    { name: "Content scale in prototype (Prototype)", win: ['z'], mac: ['z'], difficulty: "hard" },
    { name: "Run last plugin (Misc)", win: ['ctrlKey', 'altKey', 'p'], mac: ['metaKey', 'altKey', 'p'], difficulty: "easy" },
    { name: "Cursor chat (Misc)", win: ['/'], mac: ['/'], difficulty: "easy" },
    { name: "Switch to dev mode (Misc)", win: ['shiftKey', 'd'], mac: ['shiftKey', 'd'], difficulty: "hard" }
];

// This line makes the array "importable" by logic.js
export { shortcuts };
